apiVersion: apps/v1
kind: Deployment
metadata:
  name: kts-backens
  namespace: my-commands
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: kts-backend
  replicas: 1
  template: 
    metadata:
      labels: 
        app: kts-backend
    spec:
      containers:
      - name: kts-backens
        image: 194846926016.dkr.ecr.eu-central-1.amazonaws.com/kts-backens:$HASH
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_SERVER
          value: 'testappdb.cfwp7wen88ii.eu-central-1.rds.amazonaws.com'
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_DB
          value: 'mycommands'
        - name: POSTGRES_USER
          value: 'mycommands'
        - name: POSTGRES_PASSWORD
          value: '123456789'
        - name: PORT
          value: '8000'
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets: 
        - name: regcred