apiVersion: apps/v1
kind: Deployment
metadata:
  name: kts-backend
  namespace: my-commands
spec:
  minReadySeconds: 30
  selector:
    matchLabels:
      app: kts-backend
  replicas: 1
  template: 
    metadata:
      labels: 
        app: kts-backend
    spec:
      containers:
      - name: kts-backend
        image: 194846926016.dkr.ecr.eu-central-1.amazonaws.com/kts-backend:HASH
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      imagePullSecrets: 
        - name: regcred