apiVersion: v1
kind: Service
metadata:
  name: kts-frontend-service
  namespace: my-commands
spec:
  selector:
    app: kts-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer